# Samlip JCo connection infomation (Dev:)
# PROD
#sap.host=80.10.128.31
#sap.systemnumber=00
#sap.client=100
#sap.language=KO
#sap.user=BBQ902
#sap.password=Genesisbbq123!@#
#sap.pool.limit=5
#sap.pool.capacity=5


# QA
sap.host=80.10.128.36
sap.r3name=QS4
sap.systemnumber=00
sap.client=200
sap.language=KO
sap.user=BBQ902
sap.password=Genesisbbq123!@#
sap.pool.limit=5
sap.pool.capacity=5